services:
  - type: web
    name: car-price-prediction
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DISABLE_COLLECTSTATIC
        value: 1